export const adminRoleConstant = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  CHAIRMAN: 'CHAIRMAN',
  HALL_OPERATOR: 'HALL_OPERATOR',
  DEPARTMENT_OPERATOR: 'DEPARTMENT_OPERATOR',
  STUDENT: 'STUDENT',
} as const;
